SysKitTeam/docs-spdockit

installation/uninstallation-guide.md
=> reverse of change

get-to-know-spdockit/backstage-screen/subscriptions-and-alerts.md
Nisam izmjenio sadržaj bitno, malo izražavanje poboljšao, barem mislim da jesam.
=> poboljšanje teksta za subscriptione i alertse

get-to-know-spdockit/backstage-screen/index.md
Za ovaj prvi Take Snapshot nisam siguran je li smislen tekst, hoću oba slučaja naglasit.
Također nisam mjenjao folder niti ime fajla u kojemu sam našao fajl, ako ne valja požali se pa ću fixat
=> Backstage actions

get-to-know-spdockit/backstage-screen/license-management.md
Nothing really added or changed, only removed one "that" that seemed out of place.
=> license managent text transfer

get-to-know-spdockit/backstage-screen/compare-wizard.md
The original was odd, had to do some major changes (_compare currently loaded farm to a default SharePoint settings_, not sorry for changing weird things like that).
=> compare wizard transfer and update, more than a few changes were made

get-to-know-spdockit/farm-explorer-screen/servers-in-farm.md
=> servers in farm transfer and update

get-to-know-spdockit/spdockit-insights.md, how-to/spdockit-insights/configure-data-collection.md
Images and video stil missing. Added some footnotes regarding the license, seemed like a good idea to mention this somewhere. Not sure if the best option. Other open questions are in the TODO:
=> Get to know/insights

requirements/TOC.md, requirements/server-load-permission-requirements.md, requirements/sharepoint-on-premises-user-permissions-requirements.md, requirements/sharepoint-online-user-permissions-requirements.md, requirements/supported-sharepoint-editions.md, requirements/system-requirements.md
Made changes to requirements articles. Added sections about SPDocKit Online and SPDocKit Insights Agents requirements.
=> Requirements articles

activation/activation-privacy-statement.md
I've changed the wording here and want you guys to check if there are any changes you'd disapprove of. (Since this is rather sensitive information)
=> changed the wording to sound more natural

how-to/role-based-security/manage-roles.md, how-to/role-based-security/manage-users.md
Removed some stuff that stood out as irrelevant, added some stuff.
=> Role based security

configuration/configure-spdockit-database.md, configuration/configure-spdockit.md, configuration/configure-two-different-farms-in-a-same-spdockit-database.md
Added 3 new help articles
Configure SPDocKit
Configure SPDocKit Database
Configure two different Farms in a same SPDocKit database
=> Configure sp doc kit

spdockit-insights/TOC.md, spdockit-insights/insights-performance-detailed.md
A more in-depth article on how the SPDocKit Insights collects the performance data and how to use the farm performance part of SPDocKit Insights.
=> how the spdockit insights collects performance data

how-to/compare-wizard/compare-servers.md
=> added compare servers article

how-to/reports/security-audit.md, permission-management/restore-permissions.md
restore permissions and permisions audit articles
=> restore perm and permisions audit articles

configuration/configure-localdb.md
Explained how to install and manage LocalDB and what are the limitations.
=> Added new help article on how to configure LocalDB

requirements/server-load-permission-requirements.md
Explained how to get the Database Permissions report to work.
=> Added a new section about database permissions load requirements

how-to/reports/administrative-actions.md
administrative actions article
=> administrative actions article

known-issues/create-table.md
New Solution how to fix this issue which will work in all cases.
=> Create table issue

spdockit-spo/sharepoint-online.md
https://acceleratio.visualstudio.com/DefaultCollection/SPDocKit/SPDocKit%20Team/_workitems?id=30660&_a=edit
=> added some reports

spdockit-insights/insights-troubleshooting.md
malo mi je funky spominjanje ove situacije sa updejtom agenta, možda baci ljude na krivi put, ali opet ta situacija se desila čovjeku, a i pokušao sam bit što jasniji
=> updated insights troubleshooting

faq/troubleshooting/rpc-server-unavailable.md
updejtao jedan dio. nisam siguran dal može pod firewall ili bi bilo bolje da sam novu točku napravio.
=> updated firewall part

spdockit-spo/connect-to-spo.md, spdockit-spo/spo-snapshots.md
proširio sam spo-snapshots članak. otvoren sam za komentare o formi itd.
=> added some text

get-to-know-spdockit/farm-explorer-screen/farm-explorer-reports.md, how-to/TOC.md, how-to/reports/comments-and-tags.md
=> Comments and tags article added; TOC updated

installation/installation-guide.md
=> Tips and tricks example

requirements/server-load-permission-requirements.md
to retrieve Always On info, the user has to be a sysadmin
=> Always on sysadmin

requirements/system-requirements.md
=> display requirements added

requirements/system-requirements.md
added requirements for sharepoint 2019
=> added requirements for sp2019

installation/upgrade-to-the-latest-version.md
Added additional info about SPDocKit upgrade.
=> added additional information about spdockit upgrade

configure-and-extend-spdockit/backstage-screen.md, configure-and-extend-spdockit/options-wizard.md, explore-reports-and-create-documentation/analytics-and-usage-reports/analytics-and-usage-reports-screen.md, explore-reports-and-create-documentation/analytics-and-usage-reports/sharepoint-analytics.md
Changed SharePoint Analytics report name to Site Collection Analytics.
=> report name changes
